# write a github actions workflow to run npm ci and npm start and get LG_TOKEN from secrets
#

# Path: .github/workflows/run.yml

name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Run
      env:
        LG_TOKEN: ${{ secrets.LG_TOKEN }}
      run: |
          npm ci
          npm start


