name: Deployment


on:
 # schedule:
  #  - cron: '0 0 * * *'
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      LG_TOKEN:
        required: true



jobs:
  deploy:
    name: Deploy
    env:
      LG_TOKEN: ${{ secrets.LG_TOKEN }}
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm start
