on:
  push:
    branches:
    - main

jobs:  
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref_name }}
    secrets:
      LG_TOKEN: ${{ secrets.LG_TOKEN }}